@host = http://localhost:8181/api

### Register Lecturer
POST {{host}}/users/lecturers/register
Content-Type: application/json

{
  "Email": "lectureremail@gmail.com",
  "Password": "password1234",
  "FirstName": "FirstName",
  "LastName": "LastName",
  "Address": "Some address",
  "Birthday": "2023-11-10",
  "Degree": "Degree"
}

### Register Student
POST {{host}}/users/students/register
Content-Type: application/json

{
  "Email": "studentmail64@gmail.com",
  "Password": "Password1234",
  "FirstName": "FirstName",
  "LastName": "LastName",
  "Address": "Address",
  "Course": 6,
  "Birthday": "2023-11-10",
  "GroupName": "Group B"
}

### Login user
POST {{host}}/users/login
Content-Type: application/json

{
  "Email": "email@gmail.com",
  "Password": "password1234"
}