### Register Lecturer
POST http://localhost:5137/api/users/lecturers/register
Content-Type: application/json

{
  "Email": "email@gmail.com",
  "Password": "Password",
  "FirstName": "FirstName",
  "LastName": "LastName",
  "Address": "Some address",
  "Birthday": "2023-11-10",
  "Degree": "Degree"
}

### Register Student
POST http://localhost:5137/api/users/students/register
Content-Type: application/json

{
  "Email": "emails@gmail.com",
  "Password": "Password",
  "FirstName": "FirstName",
  "LastName": "LastName",
  "Address": "Address",
  "Course": 1,
  "Birthday": "2023-11-10",
  "GroupName": "Group A"
}