@host = http://localhost:5137/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImM0MTJjNzY4LTRhMGItNGNmMi1iMmE0LTAxZGVmM2VjOTA5NyIsImdpdmVuX25hbWUiOiJUaG9tYXMiLCJmYW1pbHlfbmFtZSI6IldpbGxpYW1zIiwiZW1haWwiOiJsZWN0dXJlcmVtYWlsQGdtYWlsLmNvbSIsInJvbGUiOiJMZWN0dXJlciIsImV4cCI6MTcxMjI2MDUwMSwiaXNzIjoiTE1TIiwiYXVkIjoiTE1TIn0.EqJhHGycQe66Z95mZ2enCT5ADOJ4dX2o8UKip69ocE0
@subjectId = 4fdcd308-f10e-45e6-b7b1-808e2ae22bb7

### Create a new subject
POST {{host}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  "Name": "ТРПЗalskjdjh",
  "Description": "Description about the subject",
  "GroupName": "Group B"
}

### Remove a subject
DELETE {{host}}/subjects/{{subjectId}}
Authorization: Bearer {{token}}

### Get all subjects
GET {{host}}/subjects/lecturer
Authorization: Bearer {{token}}

### Get lecturer grades
GET {{host}}/grades
Authorization: Bearer {{token}}