@host = http://localhost:5137/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjFlYTNjYjE3LTg0NzQtNDVmMS05ZDE4LTFmZWQ1YThmNmMwMiIsImdpdmVuX25hbWUiOiJGaXJzdE5hbWUiLCJmYW1pbHlfbmFtZSI6Ikxhc3ROYW1lIiwiZW1haWwiOiJzdHVkZW50RW1haWxAZ21haWwuY29tIiwicm9sZSI6IlN0dWRlbnQiLCJleHAiOjE3MTIxNDIwMTIsImlzcyI6IkxNUyIsImF1ZCI6IkxNUyJ9.M3Fr6gr7LEOCTFjCSBpKM59AAQ_M3wx89abQWncs3ts

### Get student subjects
GET {{host}}/subjects/student
Authorization: Bearer {{token}}