@host = http://localhost:8181/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjljYWVjNmQwLTc1ZDItNGUyOS1hMWI4LTg1ODYzODUxMGY0MiIsImdpdmVuX25hbWUiOiJGaXJzdE5hbWUiLCJmYW1pbHlfbmFtZSI6Ikxhc3ROYW1lIiwiZW1haWwiOiJzdHVkZW50RW1haWxAZ21haWwuY29tIiwicm9sZSI6IlN0dWRlbnQiLCJleHAiOjE3MTE0ODQwNjIsImlzcyI6IkxNUyIsImF1ZCI6IkxNUyJ9.eNCRGgYqyZg_OszLxMSaXCQKonhFpqqWEIeHtQUICIA

### Get student subjects
GET {{host}}/subjects/student
Authorization: Bearer {{token}}