@host = http://localhost:5137/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImNlZWEzZTQyLTQ3NzQtNGZiNS1hZTRkLTM5N2M2NjZlZTNlOSIsImdpdmVuX25hbWUiOiJGaXJzdE5hbWUiLCJmYW1pbHlfbmFtZSI6Ikxhc3ROYW1lIiwiZW1haWwiOiJsZWN0dXJlcmVtYWlsQGdtYWlsLmNvbSIsInJvbGUiOiJMZWN0dXJlciIsImV4cCI6MTcxMTMxMzgwNywiaXNzIjoiTE1TIiwiYXVkIjoiTE1TIn0.1U6be0mIhuZBWc0-m1T9tZ84xw6cwu4MDW3aotspeZ0
@subjectId = 4fdcd308-f10e-45e6-b7b1-808e2ae22bb7

### Create a new subject
POST {{host}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  "Name": "ТРПЗ",
  "Description": "Description about the subject",
  "GroupName": "Group B"
}

### Remove a subject
DELETE {{host}}/subjects/{{subjectId}}
Authorization: Bearer {{token}}

### Get all subjects
GET {{host}}/subjects/lecturer
Authorization: Bearer {{token}}