@host = http://localhost:5137/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjNhN2JjNzczLTUwMWItNGZiOC04NjExLTdhMjA3MWM2Mzk3NSIsImdpdmVuX25hbWUiOiJQZXRybyIsImZhbWlseV9uYW1lIjoiUGV0cm92IiwiZW1haWwiOiJlbWFpbEBnbWFpbC5jb20iLCJyb2xlIjoiTGVjdHVyZXIiLCJleHAiOjE3MDA0MzYyNDAsImlzcyI6IkxNUyIsImF1ZCI6IkxNUyJ9.G1R1-hoaTzqcEesga8Zw372c10rkGE-KTeOdFjY9WC0
@subjectId = 4fdcd308-f10e-45e6-b7b1-808e2ae22bb7

### Create a new subject
POST {{host}}/subjects
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  "Name": "Subject B",
  "Description": "Description about the subject",
  "GroupName": "Group B"
}

### Remove a subject
DELETE {{host}}/subjects/{{subjectId}}
Authorization: Bearer {{token}}

### Get all subjects
GET {{host}}/subjects
Authorization: Bearer {{token}}