GET http://localhost:5137/api/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IjM1ODk0ODliLTQ5NWQtNDkzMy1hYTgzLTJmMDAwMjRmMTdiZCIsImdpdmVuX25hbWUiOiJGaXJzdE5hbWUiLCJmYW1pbHlfbmFtZSI6Ikxhc3ROYW1lIiwiZW1haWwiOiJlbWFpbDExMTFAZ21haWwuYy5jb20iLCJyb2xlIjoiU3R1ZGVudCIsImV4cCI6MTY5OTczNzQ3MCwiaXNzIjoiTE1TIiwiYXVkIjoiTE1TIn0.txzoAQWIRG_pnd1wnoQnIHd5x7T2CyyFo57LQFzVKaU 
