@host = http://localhost:5137/api
@token = eyjhbgcioijiuzi1niisinr5cci6ikpxvcj9.eyj1bmlxdwvfbmftzsi6imnlzwezztqyltq3nzqtngzins1hztrkltm5n2m2njzlztnlosisimdpdmvux25hbwuioijgaxjzde5hbwuilcjmyw1pbhlfbmftzsi6ikxhc3royw1liiwizw1hawwioijszwn0dxjlcmvtywlsqgdtywlslmnvbsisinjvbguioijmzwn0dxjlciisimv4cci6mtcxmtmxmzgwnywiaxnzijoite1tiiwiyxvkijoite1tin0.1u6be0mihuzbwc0-m1t9tz84xw6cwu4mdw3aotspez0
@taskid = 74fe810b-6580-45ef-88cd-5d6476d4a2f0
@subjectid = 8e279316-eb68-4709-8ccf-a9453122e303

### assign new task
post {{host}}/tasks
content-type: application/json
authorization: bearer {{token}}

{
  "title": "task title",
  "description": "task description", 
  "subjectid": "{{subjectid}}",
  "deadline": "2023-11-23t19:13:18.228z",
  "maxgrade": 10
}

### remove task
delete {{host}}/tasks/{{taskid}}
authorization: bearer {{token}}

### get lecturer task details
get {{host}}/tasks/{{taskid}}
authorization: bearer {{token}}